services:
  service-1:
    image: mendhak/http-https-echo:31
    ports:
      - "${HTTP_PORT:-8080}"
    environment:
      - HTTP_PORT=${HTTP_PORT:-8080}
    networks:
      - default
      - other

  service-2:
    image: mendhak/http-https-echo:31
    ports:
      - "8080"

networks:
  default:
  other:
