parallelization: 1
tests:
- name: test-1
  setup:
    type: docker-compose
    files:
      - ./test-1/docker-compose.yaml
      - ./test-1/docker-compose.test-1.yaml
    services:
      - service-1
    envFile: ./test-1/.env
    extraEnv:
      - key: HTTP_PORT
        value: "8080"

  readyChecks:
    - type: httpGet
      url: http://localhost:{{ (index (index .Setup.Containers "service-1" ).PublishedPorts "8080").PublishedPort }}/health
      status: 200
      timeout: 60s
      requestTimeout: 5s
      interval: 5s

  runner:
    type: postman
    collections:
      - collectionFile: ./test-1/collection.postman_collection.json
        environmentFile: ./test-1/environment.json
        environmentOverrides:
          - key: port
            value: "{{ .Setup.Services.service-1.Ports.8080 }}"

  exporters:
    - type: junit
      file: ./test-1/results.xml
    - type: json
      file: ./test-1/results.json
# - name: test-2
#   setup:
#     type: none

#   readyChecks: []

#   runner:
#     type: gradle
#     workingDirectory: ./test-2
#     includedTasks:
#       - test
#       - integrationTest
#     excludedTasks:
#       - anExample

#   exporters:
#     - type: junit
#       file: ./test-1/results.xml
#     - type: json
#       file: ./test-1/results.json
# - name: test-3
#   setup:
#     type: none

#   readyChecks: []

#   runner:
#     type: go
#     workingDirectory: ./test-3
#     includedPackages:
#       - ./...
#     excludedPackages:
#       - ./vendor/...

#   exporters:
#     - type: junit
#       file: ./test-1/results.xml
#     - type: json
#       file: ./test-1/results.json

  # - name: test-4
  #   setup:
  #     type: exec
  #     commands:
  #       - go run ./test-4/main.go
  #       - command: echo hello
  #         environment:
  #         - key: FOO
  #           value: bar

  #   readyChecks: []

  #   runner:
  #     type: go
  #     workingDirectory: ./test-4
  #     includedPackages:
  #       - ./...
  #     excludedPackages:
  #       - ./vendor/...

  #   exporters:
  #     - type: junit
  #       file: ./test-4/results.xml
  #     - type: json
  #       file: ./test-4/results.json
